name: 'The fallen crown'

on:
#  push:
#    branches: [ "main" ]
#    paths:
#      - '**/preprocessor.*'
#  schedule:
#    - cron: '0 */3 * * *'
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NODE_VERSION: '20'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Lets go sweetheart
        run: php edge/The-fallen-crown.php

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes with timestamp
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "ⅣⅭ $(TZ='Asia/Tehran' date '+%H:%M:%S')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
